"""Golden characterization suite for build/bin/evaluate_point.

Freezes the CURRENT behavior of src/evaluate_point.cpp (built against the
vendored stock 2HDMC 1.8) so that any later migration, rename, or refactor can
be checked against an executable oracle. See
docs/characterization_evaluate_point.md and, at the workspace root,
SELECTIVE_MIGRATION_AUDIT.md sections 7, 8 and 10.

Two kinds of tests live here:

1. Static tests on the committed golden files
   (tests/golden/evaluate_point_v1/{input.csv,expected.csv,manifest.json}).
   These run everywhere, including the plain python CI job, and assert the
   discrete flags, invariants, NaN masks and checksums of the frozen oracle.

2. Executable tests that need build/bin/evaluate_point (built via
   scripts/build_2hdmc.sh && scripts/build_evaluate_point.sh). They re-run the
   binary on the golden input and compare against the frozen expected output,
   check repeat-run byte determinism, and check the serial-vs-sharded merge
   path. They SKIP when the binary is absent unless DHB_REQUIRE_EVALUATE_POINT=1
   is set (the dedicated CI job sets it, so absence fails loudly there).

The committed expected.csv is a GENERATED oracle (output of the current
implementation), regenerated by scripts/generate_golden_evaluate_point.py.
The assertions written out in this file (flag values, invariants, thresholds)
are the manually authored, reviewed expectations from the audit; the full
numeric record comparison uses the generated oracle.
"""

import csv
import hashlib
import json
import math
import os
import shutil
import subprocess
import sys

import pytest

from dhb import contracts, validate

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GOLDEN_DIR = os.path.join(REPO_ROOT, "tests", "golden", "evaluate_point_v1")
INPUT_CSV = os.path.join(GOLDEN_DIR, "input.csv")
EXPECTED_CSV = os.path.join(GOLDEN_DIR, "expected.csv")
MANIFEST_JSON = os.path.join(GOLDEN_DIR, "manifest.json")
BINARY = os.path.join(REPO_ROOT, "build", "bin", "evaluate_point")
CONSTRAINTS_CPP = os.path.join(
    REPO_ROOT, "lib", "2HDMC-1.8.0", "src", "Constraints.cpp"
)

REQUIRE_BINARY = os.environ.get("DHB_REQUIRE_EVALUATE_POINT") == "1"

needs_binary = pytest.mark.skipif(
    not os.path.exists(BINARY) and not REQUIRE_BINARY,
    reason=(
        "build/bin/evaluate_point not built (scripts/build_2hdmc.sh && "
        "scripts/build_evaluate_point.sh); set DHB_REQUIRE_EVALUATE_POINT=1 "
        "to make this a hard failure"
    ),
)

# Golden point ids in required row order (G01..G05, G07; no G06 here -- that
# is a main_dihiggs lambda1 case, out of scope for this repository).
GOLDEN_IDS = [
    "p1",  # G01
    "p4",  # G02
    "p5",  # G03
    "lhs_000278",  # G04
    "tiny_mH300_mA300_tb10000_l61em12_M300",  # G05
    "g07_set_param_phys_fail_mH_nextafter_below_mh",  # G07
]

FLAG_COLUMNS = [
    "set_param_phys_ok",
    "positivity_ok",
    "unitarity_ok",
    "perturbativity_ok",
    "stability_ok",
    "triple_ok",
    "theory_ok",
]

# Manually authored expectations (audit sections 7 and 10 acceptance tests),
# to be satisfied by the generated oracle AND any regenerated output.
EXPECTED_FLAGS = {
    # G01: successful construction, all theory checks pass.
    "p1": dict(zip(FLAG_COLUMNS, [1, 1, 1, 1, 1, 1, 1]))
    | {"rejection_stage": "none", "rejection_reason": "ok"},
    # G02: unitarity failure (this fixture row also fails perturbativity;
    # the reported first failure follows the evaluator's fixed precedence).
    # KNOWN COVERAGE LIMITATION: no readily available fixture point fails
    # unitarity alone, so unitarity is not isolated from perturbativity here.
    # The full flag vector below is intentionally frozen as-is; no synthetic
    # point is fabricated to stand in as physical evidence.
    "p4": dict(zip(FLAG_COLUMNS, [1, 1, 0, 0, 1, 0, 0]))
    | {"rejection_stage": "unitarity", "rejection_reason": "unitarity_failed"},
    # G03: positivity failure (== stability failure under the current alias);
    # this row also fails unitarity and perturbativity.
    "p5": dict(zip(FLAG_COLUMNS, [1, 0, 0, 0, 0, 0, 0]))
    | {"rejection_stage": "positivity", "rejection_reason": "positivity_failed"},
    # G04: perturbativity-only failure among the four primitive flags.
    "lhs_000278": dict(zip(FLAG_COLUMNS, [1, 1, 1, 0, 1, 0, 0]))
    | {
        "rejection_stage": "perturbativity",
        "rejection_reason": "perturbativity_failed",
    },
    # G05: accepted repository-threshold characterization point
    # (ctau_mm_H2 ~ 1.628e-3 mm = 1.628 micrometres; see
    # test_g05_accepted_repository_threshold_point).
    "tiny_mH300_mA300_tb10000_l61em12_M300": dict(
        zip(FLAG_COLUMNS, [1, 1, 1, 1, 1, 1, 1])
    )
    | {"rejection_stage": "none", "rejection_reason": "ok"},
    # G07: deterministic construction failure, row preserved.
    "g07_set_param_phys_fail_mH_nextafter_below_mh": dict(
        zip(FLAG_COLUMNS, [0, 0, 0, 0, 0, 0, 0])
    )
    | {
        "rejection_stage": "set_param_phys",
        "rejection_reason": "set_param_phys_returned_false",
    },
}

# hbar*c in GeV*mm as hard-coded in src/evaluate_point.cpp (kHbarCGeVmm) and
# mirrored by dhb.contracts.HBAR_C_GEV_MM. Lifetime convention:
# ctau_mm_H2 [mm] = HBAR_C_GEV_MM / total_width_H2 [GeV].
HBAR_C_GEV_MM = 1.973269804e-13

# --- per-field numeric comparison policy -----------------------------------
# Used when comparing a REGENERATED output against the frozen expected.csv.
# Same-binary reruns are covered by a separate byte-identity test; these
# tolerances exist so that a rebuild with a different (but sane) toolchain
# fails only on real behavioral drift, with a per-field diagnostic.
#
# exact  : parsed doubles must be bitwise identical (pass-through inputs and
#          compile-time constants; the evaluator copies them unmodified).
#          lambda6_derived/lambda7_derived belong here, NOT in "recon": the
#          vendored 2HDMC stores and returns them directly (get_param_gen
#          reads back the stored lambda6/lambda7), and executable evidence
#          confirms the serialized expected and regenerated values round-trip
#          to the same Float64. Any tolerance with an absolute floor would be
#          invalid for magnitudes like G05's lambda6 = 1e-12 and would let an
#          actual 0.0 pass against an expected 1e-12. Fallback policy if a
#          future toolchain legitimately breaks bit-identity here: rel <=
#          5e-15 with abs = 0, and an expected zero still requires an actual
#          zero — never reintroduce a broad absolute floor.
# tight  : one libm call away from inputs (atan/sin/cos), <= few ULP.
# recon  : 2HDMC coupling/parameter reconstruction; algebra with cancellation
#          whose absolute noise floor is ~1e-13..1e-12 for these magnitudes
#          (e.g. lambda4 ~ -1e-8 on p1 is itself a cancellation residual).
# resid  : the M2 reconstruction relative-error column, a pure residual
#          (~1e-14); only an absolute bound is meaningful.
# loop   : DecayTable widths / BRs / lifetime and the HBHS block: loop-level
#          numerics through GSL/libm; tiny values like width_hh_H2 ~ 6e-32
#          are cancellation residuals of an exactly-zero coupling, hence the
#          absolute floor.
FIELD_GROUPS = {
    "exact": {
        "fields": {
            "mh",
            "mH",
            "mA",
            "mHp",
            "tan_beta",
            "sin_ba",
            "lambda6_input",
            "lambda7_input",
            "lambda6_derived",
            "lambda7_derived",
            "M",
            "M2",
        },
        "rel": 0.0,
        "abs": 0.0,
    },
    "tight": {
        "fields": {"beta", "m12_sq_input"},
        "rel": 1e-15,
        "abs": 0.0,
    },
    "recon": {
        "fields": {
            "lambda1",
            "lambda2",
            "lambda3",
            "lambda4",
            "lambda5",
            "m12_sq_derived",
            "tan_beta_derived",
            "M2_recomputed",
        },
        "rel": 1e-12,
        "abs": 1e-11,
    },
    "resid": {
        "fields": {"relative_M2_reconstruction_error"},
        "rel": 0.0,
        "abs": 1e-11,
    },
    # "loop" is the fallback for every remaining float column (widths, BRs,
    # ctau and the whole HBHS block), assigned in field_tolerance().
}
LOOP_REL = 1e-10
LOOP_ABS = 1e-24

STRING_EXACT_COLUMNS = {
    "point_id",
    "yukawa_assignment",
    "scalar_z2_status",
    "rejection_stage",
    "rejection_reason",
}
INT_EXACT_COLUMNS = set(FLAG_COLUMNS) | {"soft_z2_only", "hbhs_block_ok"}


def field_tolerance(column):
    """Return (group_name, rel, abs) for a float column."""
    for name, spec in FIELD_GROUPS.items():
        if column in spec["fields"]:
            return name, spec["rel"], spec["abs"]
    return "loop", LOOP_REL, LOOP_ABS


def floats_match(a, b, rel, abs_tol):
    """Compare expected `a` against actual `b` under (rel, abs_tol).

    Non-finite values are classified BEFORE any tolerance arithmetic, so no
    NaN or infinity ever enters the tolerance formula:
      - NaN matches only NaN (the expected NaN-mask contract);
      - an infinity matches only an infinity of the same sign;
      - any infinity-vs-finite (either direction) fails;
      - only finite-vs-finite reaches the tolerance comparison.
    """
    if math.isnan(a) or math.isnan(b):
        return math.isnan(a) and math.isnan(b)
    if math.isinf(a) or math.isinf(b):
        return a == b
    if a == b:
        return True
    if rel == 0.0 and abs_tol == 0.0:
        return False
    return abs(a - b) <= max(rel * max(abs(a), abs(b)), abs_tol)


def assert_row_lengths(header, rows, kind):
    """Assert every row has exactly len(header) fields.

    Guards the zip()-based field comparisons, which would otherwise silently
    drop trailing fields on a truncated row (zip stops at the shorter side).
    `kind` labels the side being checked ("expected" or "actual").
    """
    for idx, row in enumerate(rows):
        pid = row[0] if row else "<empty row>"
        assert len(row) == len(header), (
            "%s row %d (point_id=%s): has %d fields, header has %d"
            % (kind, idx, pid, len(row), len(header))
        )


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def read_csv(path):
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        header = next(reader)
        rows = list(reader)
    return header, rows


@pytest.fixture(scope="module")
def manifest():
    with open(MANIFEST_JSON, encoding="utf-8") as f:
        return json.load(f)


@pytest.fixture(scope="module")
def golden_input():
    return read_csv(INPUT_CSV)


@pytest.fixture(scope="module")
def golden_expected():
    return read_csv(EXPECTED_CSV)


@pytest.fixture(scope="module")
def expected_by_id(golden_expected):
    header, rows = golden_expected
    return {row[0]: dict(zip(header, row)) for row in rows}


def run_evaluate_point(input_csv, output_csv):
    if not os.path.exists(BINARY):
        pytest.fail(
            "DHB_REQUIRE_EVALUATE_POINT=1 but %s is missing; run "
            "scripts/build_2hdmc.sh && scripts/build_evaluate_point.sh" % BINARY
        )
    subprocess.run(
        [BINARY, str(input_csv), str(output_csv)],
        check=True,
        capture_output=True,
        cwd=REPO_ROOT,
    )


# ---------------------------------------------------------------------------
# Static tests on the committed golden files
# ---------------------------------------------------------------------------


def test_manifest_checksums_and_row_counts(manifest, golden_input, golden_expected):
    assert manifest["golden_suite"] == "evaluate_point_v1"
    assert manifest["files"]["input.csv"]["sha256"] == sha256_file(INPUT_CSV)
    assert manifest["files"]["expected.csv"]["sha256"] == sha256_file(EXPECTED_CSV)
    assert manifest["files"]["input.csv"]["data_rows"] == len(golden_input[1])
    assert manifest["files"]["expected.csv"]["data_rows"] == len(golden_expected[1])


def test_row_cardinality_and_stable_order(golden_input, golden_expected):
    """One output row per input row, same point_id, same order.

    In particular the G07 construction failure must NOT be dropped.
    """
    input_ids = [row[0] for row in golden_input[1]]
    output_ids = [row[0] for row in golden_expected[1]]
    assert input_ids == GOLDEN_IDS
    assert output_ids == GOLDEN_IDS


def test_golden_case_flags_and_rejection(expected_by_id):
    """Exact discrete behavior of each golden case (audit sections 7/10)."""
    assert set(expected_by_id) == set(EXPECTED_FLAGS)
    for pid, expected in EXPECTED_FLAGS.items():
        row = expected_by_id[pid]
        for col, want in expected.items():
            got = row[col]
            assert got == str(want), (
                "golden %s: column %s expected %r got %r" % (pid, col, want, got)
            )


def test_g01_partial_widths_positive(expected_by_id):
    row = expected_by_id["p1"]
    for col in (
        "width_gammagamma_H2",
        "width_Zgamma_H2",
        "width_bb_H2",
        "width_gg_H2",
        "total_width_H2",
    ):
        assert float(row[col]) > 0.0, "%s must be strictly positive on G01" % col


def test_accepted_rows_have_finite_nonnegative_widths(expected_by_id):
    width_cols = [
        "width_bb_H2",
        "width_tautau_H2",
        "width_WW_H2",
        "width_ZZ_H2",
        "width_gammagamma_H2",
        "width_Zgamma_H2",
        "width_gg_H2",
        "width_hh_H2",
        "total_width_H2",
    ]
    for pid, row in expected_by_id.items():
        if row["theory_ok"] != "1":
            continue
        for col in width_cols:
            value = float(row[col])
            assert math.isfinite(value) and value >= 0.0, (
                "golden %s: %s = %r must be finite and nonnegative" % (pid, col, value)
            )


def test_g05_accepted_repository_threshold_point(expected_by_id):
    """G05 is an accepted repository-threshold characterization point:
    ctau_mm_H2 ~ 1.628e-3 mm = 1.628 micrometres, which sits above the
    historical repository threshold of 1e-3 mm. Crossing that threshold is a
    frozen repository behavior, NOT evidence of an experimentally displaced
    or physically long-lived signature (1.628 micrometres is far below any
    detector displacement scale)."""
    row = expected_by_id["tiny_mH300_mA300_tb10000_l61em12_M300"]
    assert row["theory_ok"] == "1"
    ctau = float(row["ctau_mm_H2"])
    assert math.isfinite(ctau)
    assert ctau >= 1e-3, (
        "G05 must stay above the historical 1e-3 mm repository threshold "
        "(characterization of repository behavior only)"
    )


def test_g07_failed_construction_row_preserved(expected_by_id):
    row = expected_by_id["g07_set_param_phys_fail_mH_nextafter_below_mh"]
    assert row["set_param_phys_ok"] == "0"
    # Raw inputs survive on the failed row...
    assert float(row["mH"]) == math.nextafter(125.09, -math.inf)
    assert float(row["mA"]) == 300.0
    assert float(row["tan_beta"]) == 50.0
    assert float(row["M"]) == 300.0
    # ...and everything computed after the failed construction is NaN.
    for col in (
        "lambda1",
        "lambda2",
        "lambda3",
        "lambda4",
        "lambda5",
        "m12_sq_derived",
        "tan_beta_derived",
        "M2_recomputed",
        "relative_M2_reconstruction_error",
        "total_width_H2",
        "br_gammagamma_H2",
        "ctau_mm_H2",
    ):
        assert math.isnan(float(row[col])), (
            "G07 column %s must be NaN, got %r" % (col, row[col])
        )
    assert row["hbhs_block_ok"] == "0"


def test_flag_relationships_match_evaluator(expected_by_id):
    """Freeze the current boolean structure of the theory flags.

    triple_ok  == positivity_ok && unitarity_ok && perturbativity_ok
    theory_ok  == set_param_phys_ok && triple_ok && stability_ok && width_ok
    where width_ok means total_width_H2 is finite and > 0.
    """
    for pid, row in expected_by_id.items():
        flags = {c: row[c] == "1" for c in FLAG_COLUMNS}
        assert flags["triple_ok"] == (
            flags["positivity_ok"]
            and flags["unitarity_ok"]
            and flags["perturbativity_ok"]
        ), pid
        width = float(row["total_width_H2"])
        width_ok = math.isfinite(width) and width > 0.0
        assert flags["theory_ok"] == (
            flags["set_param_phys_ok"]
            and flags["triple_ok"]
            and flags["stability_ok"]
            and width_ok
        ), pid


def test_positivity_stability_alias_in_data(expected_by_id):
    """CHARACTERIZATION, not a physics requirement: with the vendored stock
    2HDMC, positivity_ok and stability_ok cannot differ because both wrappers
    call the same underlying model check. If this ever fails, the dependency
    (or its patch state) changed and the golden suite must be regenerated and
    re-reviewed -- do NOT silently accept independent values.
    """
    for pid, row in expected_by_id.items():
        if row["set_param_phys_ok"] != "1":
            continue
        assert row["positivity_ok"] == row["stability_ok"], (
            "golden %s: positivity_ok=%s stability_ok=%s -- the current "
            "vendored 2HDMC aliases these checks; see "
            "docs/characterization_evaluate_point.md" % (
                pid, row["positivity_ok"], row["stability_ok"],
            )
        )


def test_positivity_stability_alias_in_vendored_source():
    """Contract check on the exact vendored source being built:
    Constraints::check_positivity() and Constraints::check_stability() both
    return model.check_stability() in stock 2HDMC 1.8. This makes the alias
    visible; it deliberately does not rename or 'fix' anything.
    """
    with open(CONSTRAINTS_CPP, encoding="utf-8", errors="replace") as f:
        source = f.read()

    import re

    def body_of(function_name):
        pattern = (
            r"bool\s+Constraints::%s\s*\(\s*\)\s*\{(.*?)\}" % function_name
        )
        match = re.search(pattern, source, re.DOTALL)
        assert match, "cannot locate Constraints::%s in %s" % (
            function_name,
            CONSTRAINTS_CPP,
        )
        return match.group(1)

    positivity_body = body_of("check_positivity")
    stability_body = body_of("check_stability")
    assert "return model.check_stability();" in positivity_body
    assert "return model.check_stability();" in stability_body


def test_m2_reconstruction_invariant(expected_by_id):
    """M2_recomputed == m12_sq_derived / (sin(beta) * cos(beta)), and the
    evaluator's own relative reconstruction error stays below a frozen bound.
    """
    for pid, row in expected_by_id.items():
        if row["set_param_phys_ok"] != "1":
            continue
        beta = float(row["beta"])
        m12_sq_derived = float(row["m12_sq_derived"])
        m2_recomputed = float(row["M2_recomputed"])
        recomputed_here = m12_sq_derived / (math.sin(beta) * math.cos(beta))
        # Python libm may differ from the C++ libm by ~1 ULP in sin/cos.
        assert floats_match(m2_recomputed, recomputed_here, 1e-13, 0.0), (
            "golden %s: M2_recomputed=%r vs m12_sq_derived/(sb*cb)=%r"
            % (pid, m2_recomputed, recomputed_here)
        )
        rel_err = float(row["relative_M2_reconstruction_error"])
        assert rel_err < 1e-9, (
            "golden %s: relative_M2_reconstruction_error=%r above frozen 1e-9"
            % (pid, rel_err)
        )


def test_ctau_lifetime_invariant(expected_by_id):
    """ctau_mm_H2 == hbar*c[GeV*mm] / total_width_H2[GeV], with the constant
    1.973269804e-13 GeV*mm frozen in src/evaluate_point.cpp and mirrored by
    dhb.contracts.HBAR_C_GEV_MM. 17-digit serialization round-trips exactly,
    so this division reproduces at Float64 precision.
    """
    assert HBAR_C_GEV_MM == contracts.HBAR_C_GEV_MM
    for pid, row in expected_by_id.items():
        width = float(row["total_width_H2"])
        ctau = float(row["ctau_mm_H2"])
        if not (math.isfinite(width) and width > 0.0):
            assert math.isnan(ctau), pid
            continue
        assert floats_match(ctau, HBAR_C_GEV_MM / width, 1e-15, 0.0), (
            "golden %s: ctau_mm_H2=%r vs hbar_c/width=%r"
            % (pid, ctau, HBAR_C_GEV_MM / width)
        )


def test_expected_csv_satisfies_theory_contract():
    report = validate.validate_csv(EXPECTED_CSV, contracts.THEORY)
    assert report.ok, report.describe()


def test_synthetic_theory_ok_boolean_logic():
    """SYNTHETIC (non-physics): pure boolean-combination check of the
    documented acceptance expression

        theory_ok = set_param_phys_ok && triple_ok && stability_ok && width_ok

    The current stock 2HDMC cannot produce a physical point with triple_ok=1
    and stability_ok=0 (positivity and stability are aliased), so this
    combination is exercised only as a synthetic record here to prove the
    expression would still veto it.
    """

    def theory_ok(set_ok, triple, stability, width_ok):
        return set_ok and triple and stability and width_ok

    synthetic_record = dict(set_ok=True, triple=True, stability=False, width_ok=True)
    assert theory_ok(**synthetic_record) is False
    assert theory_ok(True, True, True, True) is True
    assert theory_ok(False, True, True, True) is False
    assert theory_ok(True, True, True, False) is False


# ---------------------------------------------------------------------------
# Comparator and row-shape self-tests (guard the guards)
# ---------------------------------------------------------------------------


def test_floats_match_non_finite_handling():
    """Non-finite classification precedes the tolerance formula: infinities
    match only same-signed infinities; infinity-vs-finite fails in both
    directions; NaN matches only NaN."""
    inf = math.inf
    rel, abs_tol = 1e-10, 1e-24  # the widest ("loop") policy in this suite
    assert floats_match(1.0, inf, rel, abs_tol) is False
    assert floats_match(inf, 1.0, rel, abs_tol) is False
    assert floats_match(inf, inf, rel, abs_tol) is True
    assert floats_match(inf, -inf, rel, abs_tol) is False
    assert floats_match(-inf, -inf, rel, abs_tol) is True
    assert floats_match(-inf, inf, rel, abs_tol) is False
    assert floats_match(1.0, -inf, rel, abs_tol) is False
    assert floats_match(-inf, 1.0, rel, abs_tol) is False
    # NaN-mask contract: NaN pairs pass; NaN against anything else fails.
    nan = math.nan
    assert floats_match(nan, nan, rel, abs_tol) is True
    assert floats_match(nan, 1.0, rel, abs_tol) is False
    assert floats_match(1.0, nan, rel, abs_tol) is False
    assert floats_match(nan, inf, rel, abs_tol) is False
    assert floats_match(inf, nan, rel, abs_tol) is False
    # The same classification holds under an exact (0, 0) policy.
    assert floats_match(inf, inf, 0.0, 0.0) is True
    assert floats_match(inf, -inf, 0.0, 0.0) is False


def test_row_length_guard_detects_truncated_and_overlong_rows():
    """Removing a trailing field (or appending a spurious one) must be
    detected by assert_row_lengths, never silently absorbed by zip()."""
    header = ["point_id", "a", "b"]
    assert_row_lengths(header, [["p1", "1", "2"]], "expected")  # exact: passes

    truncated = [["p1", "1"]]  # trailing field removed
    with pytest.raises(AssertionError) as excinfo:
        assert_row_lengths(header, truncated, "actual")
    message = str(excinfo.value)
    assert "actual" in message
    assert "p1" in message
    assert "has 2 fields" in message
    assert "header has 3" in message

    overlong = [["p2", "1", "2", "3"]]
    with pytest.raises(AssertionError) as excinfo:
        assert_row_lengths(header, overlong, "expected")
    message = str(excinfo.value)
    assert "expected" in message
    assert "p2" in message
    assert "has 4 fields" in message
    assert "header has 3" in message


def test_golden_files_have_consistent_field_counts(golden_input, golden_expected):
    """Every data row in the committed golden files must have exactly as many
    fields as its header (truncated/overlong rows are corruption)."""
    in_header, in_rows = golden_input
    assert_row_lengths(in_header, in_rows, "expected")
    exp_header, exp_rows = golden_expected
    assert_row_lengths(exp_header, exp_rows, "expected")


def test_lambda67_derived_policy_is_exact_and_rejects_zero_for_1em12():
    """Regression for the invalid 1e-11 absolute floor: lambda6_derived /
    lambda7_derived are pass-through values (G05 has lambda6 = 1e-12), so
    their policy must be exact, and an actual 0.0 must FAIL against an
    expected 1e-12 (and vice versa)."""
    for column in ("lambda6_derived", "lambda7_derived"):
        group, rel, abs_tol = field_tolerance(column)
        assert group == "exact"
        assert rel == 0.0 and abs_tol == 0.0
        assert floats_match(1e-12, 0.0, rel, abs_tol) is False
        assert floats_match(0.0, 1e-12, rel, abs_tol) is False
        assert floats_match(0.0, 0.0, rel, abs_tol) is True
        assert floats_match(1e-12, 1e-12, rel, abs_tol) is True


def test_lambda67_derived_pass_through_invariant(expected_by_id):
    """The vendored 2HDMC stores lambda6/lambda7 and returns them unmodified,
    so on every constructed row lambda{6,7}_derived must equal
    lambda{6,7}_input EXACTLY (an expected zero requires an actual zero), and
    on failed construction they must be NaN."""
    for pid, row in expected_by_id.items():
        for input_col, derived_col in (
            ("lambda6_input", "lambda6_derived"),
            ("lambda7_input", "lambda7_derived"),
        ):
            derived = float(row[derived_col])
            if row["set_param_phys_ok"] != "1":
                assert math.isnan(derived), (
                    "golden %s: %s must be NaN on failed construction, got %r"
                    % (pid, derived_col, row[derived_col])
                )
                continue
            passed_in = float(row[input_col])
            assert derived == passed_in, (
                "golden %s: %s=%r must exactly equal %s=%r (pass-through)"
                % (pid, derived_col, row[derived_col], input_col, row[input_col])
            )
            if passed_in == 0.0:
                assert derived == 0.0


# ---------------------------------------------------------------------------
# Executable tests (need build/bin/evaluate_point)
# ---------------------------------------------------------------------------


@needs_binary
def test_regenerated_output_matches_golden(tmp_path, golden_expected):
    """Re-run the compiled evaluator on the committed golden input and compare
    against the frozen expected.csv with the per-field policy above."""
    out_csv = tmp_path / "evaluate_point.csv"
    run_evaluate_point(INPUT_CSV, out_csv)

    exp_header, exp_rows = golden_expected
    got_header, got_rows = read_csv(str(out_csv))

    assert got_header == exp_header, "output header drifted"
    assert len(got_rows) == len(exp_rows), "row cardinality drifted"
    # zip() below stops at the shorter side, so truncated/overlong rows must
    # be rejected explicitly before any field-by-field comparison.
    assert_row_lengths(exp_header, exp_rows, "expected")
    assert_row_lengths(exp_header, got_rows, "actual")

    failures = []
    for exp_row, got_row in zip(exp_rows, got_rows):
        pid = exp_row[0]
        for col, exp_text, got_text in zip(exp_header, exp_row, got_row):
            if col in STRING_EXACT_COLUMNS or col in INT_EXACT_COLUMNS:
                if exp_text != got_text:
                    failures.append(
                        "%s.%s: expected %r got %r (exact)" % (pid, col, exp_text, got_text)
                    )
                continue
            exp_val = float(exp_text)
            got_val = float(got_text)
            group, rel, abs_tol = field_tolerance(col)
            if not floats_match(exp_val, got_val, rel, abs_tol):
                failures.append(
                    "%s.%s: expected %r got %r (group=%s rel=%g abs=%g)"
                    % (pid, col, exp_text, got_text, group, rel, abs_tol)
                )
    assert not failures, "golden mismatch:\n  " + "\n  ".join(failures)


@needs_binary
def test_repeat_serial_runs_byte_identical(tmp_path):
    out_a = tmp_path / "run_a.csv"
    out_b = tmp_path / "run_b.csv"
    run_evaluate_point(INPUT_CSV, out_a)
    run_evaluate_point(INPUT_CSV, out_b)
    assert out_a.read_bytes() == out_b.read_bytes(), (
        "two consecutive serial runs of the same binary on the same input "
        "must produce byte-identical CSV"
    )


@needs_binary
def test_serial_vs_two_shard_merge(tmp_path):
    """The repository's supported sharded path (scripts/split_point_csv.py +
    scripts/merge_shard_outputs.py) must reproduce the serial scientific rows
    exactly, in the same stable point order."""
    serial_csv = tmp_path / "serial.csv"
    run_evaluate_point(INPUT_CSV, serial_csv)

    shards_dir = tmp_path / "shards"
    subprocess.run(
        [
            sys.executable,
            os.path.join(REPO_ROOT, "scripts", "split_point_csv.py"),
            "--input",
            INPUT_CSV,
            "--outdir",
            str(shards_dir),
            "--n-shards",
            "2",
        ],
        check=True,
        capture_output=True,
    )
    for shard in sorted(os.listdir(shards_dir)):
        shard_dir = shards_dir / shard
        if not shard_dir.is_dir():
            continue
        run_evaluate_point(shard_dir / "points.csv", shard_dir / "evaluate_point.csv")

    merged_csv = tmp_path / "merged.csv"
    subprocess.run(
        [
            sys.executable,
            os.path.join(REPO_ROOT, "scripts", "merge_shard_outputs.py"),
            "--shards-dir",
            str(shards_dir),
            "--output",
            str(merged_csv),
        ],
        check=True,
        capture_output=True,
    )

    serial_header, serial_rows = read_csv(str(serial_csv))
    merged_header, merged_rows = read_csv(str(merged_csv))
    assert merged_header == serial_header
    assert merged_rows == serial_rows, (
        "merged shard output must equal the serial output field-for-field"
    )
